### ISSUE TITLE
是否可以给各种原生组件的事件拓展类型?

### ISSUE THREAD

**Issue by mutoe** [MS-DG/api-typings#17]
### 痛点
比如 input 组件中的 `bind:input` 事件,每次用 `event.Custom` 类型 时, `detail` 都是 `any`, 这很不爽

<img width="326" alt="图片" src="https://user-images.githubusercontent.com/9391981/60765763-04771480-a0d2-11e9-8057-025e7e8ead4a.png">

现在想给 bind:input 指定一个类型, 有2种方法
### 1. 给event参数指定类型
``` ts
declare namespace event {
  type InputInput = Custom<{
    value: string
    cursor: number
    keyCode?: number
  }>
}
```
<img width="447" alt="图片" src="https://user-images.githubusercontent.com/9391981/60765822-ebbb2e80-a0d2-11e9-8129-00b99977cb59.png">

### 2. 给方法指定接口类型
``` ts
type InputOnInput = (
  event: event.Custom<{
    value: string
    cursor: number
    keyCode?: number
  }>,
) => string | void
```

<img width="438" alt="图片" src="https://user-images.githubusercontent.com/9391981/60765977-5bcab400-a0d5-11e9-88bb-cf8bbb4f00b8.png">

这是我能想到的两种方法,  至于为什么会有 `InputInput` 这种类型名, 是因为这是表示 `<input>` 下的 `bind:input` 的方法

----

不知道是否有必要这样定义, 如果可以, 能否给予一些建议, 比如这种类型定义是写在 namespace event 下还是其他文件下, 我稍后将给予一个PR

**Comment by NewFuture** [comment]
这个种自带事件的定义确实很常用

我觉得放在`event`下可能比较合适,和现在得touch等其实是同一类型的。

至于onInput这种,约束返回值有用但是对于使用的场景可能效果不如前面的简单方便。

**Comment by mutoe** [comment]
@NewFuture OK 开始动工了 😄

**Comment by NewFuture** [comment]
merged
