### ISSUE TITLE
能否完善下behavior声明文件

### ISSUE THREAD

**Issue by heng1025** [MS-DG/api-typings#22]
官方文档 https://developers.weixin.qq.com/miniprogram/dev/reference/api/Behavior.html

**Comment by NewFuture** [comment]
有空的时候加一下

**Comment by NewFuture** [comment]
@heng1025  这个已经 加上了 #23

可以试试 
```bash
npm i -D MS-DG/api-typings
```

**Comment by heng1025** [comment]
感谢

**Comment by heng1025** [comment]
在component怎样自动推断behavior中的数据和方法

**Comment by heng1025** [comment]
> 在component怎样自动推断behavior中的数据和方法

 WxComponent<TProp, TData, TMethod> 可以声明一个methods属性，然后通过获取behavior的methods返回值，合并到component的methods中

**Comment by NewFuture** [comment]
behaviors 和component之间实现自动类型推断和绑定似乎有些困难

这个和vue的混合有类似的问题
https://forum.vuejs.org/t/using-mixins-with-typescript/24256

**Comment by heng1025** [comment]
折腾了一上午，最后使用了// @ts-ignore
