### ISSUE TITLE
ComponentOptions没有跟进文档

### ISSUE THREAD

**Issue by Mister-Hope** [MS-DG/api-typings#30]
文档：
---

#### 组件样式隔离

默认情况下，自定义组件的样式只受到自定义组件 wxss 的影响。除非以下两种情况：

app.wxss 或页面的 wxss 中使用了标签名选择器（或一些其他特殊选择器）来直接指定样式，这些选择器会影响到页面和全部组件。通常情况下这是不推荐的做法。
指定特殊的样式隔离选项 styleIsolation 。

```js
Component({
  options: {
    styleIsolation: 'isolated'
  }
})
```

styleIsolation 选项从基础库版本 2.6.5 开始支持。它支持以下取值：

isolated 表示启用样式隔离，在自定义组件内外，使用 class 指定的样式将不会相互影响（一般情况下的默认值）；
apply-shared 表示页面 wxss 样式将影响到自定义组件，但自定义组件 wxss 中指定的样式不会影响页面；
shared 表示页面 wxss 样式将影响到自定义组件，自定义组件 wxss 中指定的样式也会影响页面和其他设置了 apply-shared 或 shared 的自定义组件。（这个选项在插件中不可用。）

---

所以

```ts
declare interface ComponentOptions {
  multipleSlots?: boolean;
  addGlobalClass?: boolean;
}
```

应改为

```ts
declare interface ComponentOptions {
  /** 是否启用多插槽支持 */
  multipleSlots?: boolean;
  /** 是否启用全局class样式支持 */
  addGlobalClass?: boolean;
  /** 
   * 样式隔离选项支持
   *
   * 最低基础库： `2.6.5`
   * 
   * 只支持以下取值：
   * - `isolated` 表示启用样式隔离，在自定义组件内外，使用 class 指定的样式将不会相互影响（一般情况下的默认值）；
   * - `apply-shared` 表示页面 wxss 样式将影响到自定义组件，但自定义组件 wxss 中指定的样式不会影响页面；
   * - `shared` 表示页面 wxss 样式将影响到自定义组件，自定义组件 wxss 中指定的样式也会影响页面和其他设置了 apply-shared 或 shared 的自定义组件。（这个选项在插件中不可用。）
   */
  styleIsolation?: 'isolated' | 'apply-shared' | 'shared'
}
```

（我同时加了一些jsdoc）

**Comment by NewFuture** [comment]
这个确实没更新,可以直接发个PR 👍
