### ISSUE TITLE
此处的value在官方文档里面应该没有number[]类型，而是number类型

### ISSUE THREAD

**Issue by loveholly** [MS-DG/api-typings#32]
https://github.com/MS-DG/api-typings/blob/edbb6ba5f2fd3be00b0f4fa8c8672442a2405e4c/types/wx/lib.event.d.ts#L448

[官方文档](https://developers.weixin.qq.com/miniprogram/dev/component/picker.html)

**Comment by NewFuture** [comment]
@mutoe 帮忙确认一下

**Comment by mutoe** [comment]
@loveholly 刚才测试了一下,在 multiSelector 模式下, 会返回 `[1,2]` 类似的数组
我的最低基础库是 `2.5.0` 你那边是什么环境呢

**Comment by loveholly** [comment]
@mutoe multiSelector我没测试，不好意思，我测试了`selector `模式，只会返回一个数字，但是在我们的库里面没有`number`类型

**Comment by mutoe** [comment]
@loveholly selector 模式返回的应该是个字符串吧?
``` xml
<picker mode="selector" bind:change="onChange" range="{{ [1, 2, 3] }}">test</picker>
```

``` ts
  onChange(e: event.PickerChange) {
    console.log(e.detail)
  },
```

got
![图片](https://user-images.githubusercontent.com/9391981/62997167-e43d3100-be99-11e9-8abe-5748c9de3400.png)

**Comment by mutoe** [comment]
@loveholly  当时写的时候也做过一些测试, 任何模式下都不会直接返回 number 类型

https://github.com/MS-DG/api-typings/blob/edbb6ba5f2fd3be00b0f4fa8c8672442a2405e4c/types/wx/lib.event.d.ts#L438-L453

注意440行, 这个返回的是value, 不是索引

**Comment by loveholly** [comment]
不好意思，确实是我搞错了，再加上被官方文档误导了。。。

**Comment by NewFuture** [comment]
小程序的文档目前确实还有不少地方写的是有问题的 😂
